# Generated by Django 5.1.3 on 2025-04-16 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_entry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalentry",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journal_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
