# Generated by Django 5.1.3 on 2025-04-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_journalentry_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_data_sync_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
