# Generated by Django 5.1.3 on 2025-04-16 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_last_data_sync_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_sync_time",
        ),
    ]
