# Generated by Django 5.1.3 on 2025-04-25 05:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_sync_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "sync_status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "未同步"),
                            (1, "同步中"),
                            (2, "同步完成"),
                            (3, "同步失败"),
                        ],
                        default=0,
                    ),
                ),
                ("conflict_count", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "同步记录",
                "verbose_name_plural": "同步记录",
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "创建"), (1, "更新"), (2, "删除")]
                    ),
                ),
                ("entity_type", models.CharField(max_length=50)),
                ("entity_id", models.CharField(max_length=100)),
                (
                    "operation_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="sync.syncrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "同步日志",
                "verbose_name_plural": "同步日志",
            },
        ),
    ]
