# Generated by Django 5.1.3 on 2025-04-13 07:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="is_synced",
            field=models.BooleanField(default=False, help_text="是否已同步到服务器"),
        ),
        migrations.AddField(
            model_name="category",
            name="sync_id",
            field=models.CharField(
                blank=True,
                help_text="用于客户端同步的唯一标识",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="journal_images/"),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="is_synced",
            field=models.BooleanField(default=False, help_text="是否已同步到服务器"),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="sync_id",
            field=models.CharField(
                blank=True,
                help_text="用于客户端同步的唯一标识",
                max_length=100,
                null=True,
            ),
        ),
    ]
