# Generated by Django 5.1.3 on 2025-04-13 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0002_category_created_at_category_is_synced_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageSyncQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(help_text="请求同步的设备ID", max_length=100),
                ),
                (
                    "original_filename",
                    models.CharField(help_text="原始文件名", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待同步"),
                            ("syncing", "同步中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("error_message", models.TextField(blank=True, help_text="错误信息")),
                (
                    "journal_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_sync_records",
                        to="api.journalentry",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_sync_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "图片同步队列",
                "verbose_name_plural": "图片同步队列",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncConflict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(help_text="发生冲突的设备ID", max_length=100),
                ),
                (
                    "conflict_type",
                    models.CharField(
                        choices=[("entry", "日志条目"), ("category", "分类")],
                        help_text="冲突类型",
                        max_length=20,
                    ),
                ),
                ("object_id", models.IntegerField(help_text="冲突对象ID")),
                ("sync_id", models.CharField(help_text="同步ID", max_length=100)),
                ("client_data", models.JSONField(help_text="客户端数据")),
                ("server_data", models.JSONField(help_text="服务器数据")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="创建时间"),
                ),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[
                            ("pending", "待解决"),
                            ("client_win", "客户端优先"),
                            ("server_win", "服务器优先"),
                            ("manual", "手动解决"),
                        ],
                        default="pending",
                        help_text="解决状态",
                        max_length=20,
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, help_text="解决时间", null=True),
                ),
                (
                    "resolution_notes",
                    models.TextField(blank=True, help_text="解决说明"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_conflicts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "同步冲突",
                "verbose_name_plural": "同步冲突",
                "ordering": ["-created_at"],
            },
        ),
    ]
